---
stages:
    - build
    - push
    - deploy

include:
    project: "lib/gitlab-ci"
    ref: master
    file:
        - "templates/gitlab-ci/docker/variables.yml"
        - "templates/gitlab-ci/docker/build.yml"
        - "templates/gitlab-ci/docker/image_push.yml"
        - "templates/gitlab-ci/docker/deploy.yml"
