version: "3.8"

services:
  app:
    build: .
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "postgres:11"
    env_file: .env
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d:ro"
      - "./volumes/db/data:/var/lib/postgresql/data"
