version: '3.8'

services:
  app:
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: 'postgres:16'
    env_file: .env
    restart: unless-stopped
    volumes:
      - './sql:/docker-entrypoint-initdb.d:ro'
      - './volumes/db/data:/var/lib/postgresql/data'
